FROM node:18-alpine AS builder

WORKDIR /app

COPY ./package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.23 AS server

COPY --from=builder ./app/out /usr/share/nginx/html

COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf