version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "4000:4000"
  postgres_db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - production.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /postgres-data:/var/lib/postgresql/data  # Named volume for data storage
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  dbdata: