# Production Dockerfile
version: '3.8'
services:
  # NextJS frontend
  frontend:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
  # NGINX client
  client:
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"   # Certbot renew script
    depends_on:
      - frontend
    ports:
      - "3000:80"
    volumes:
      - ./etc/nginx.dev.conf:/etc/nginx/nginx.conf
  # Express backend
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "4000:4000"
    env_file:
      - ./backend/dev.env
  # Postgres DB
  postgres_db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - db.dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql  # DB Initialization script
      - /postgres-data-dev:/var/lib/postgresql/data  # Named volume for data storage
volumes:
  dbdata: