PUT http://localhost:4000/api/photo/TZmx8jIhKE
Content-Type: application/json

{
  "title": "This is the updated title",
  "description": "This is the updated description",
  "favorite": "true",
  "categories": ["hello", "world"]
}

###

PUT http://localhost:4000/api/photo/vwv1eJkXzW
Content-Type: application/json

{
  "title": "This is the updated title"
}

###
